# Generated by Django 5.2.8 on 2025-11-23 08:06

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('element_id', models.UUIDField(default=core.models.generate_uuid)),
                ('html_content', models.TextField(blank=True, null=True)),
                ('children', models.ManyToManyField(blank=True, to='core.element')),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('html_content', models.TextField(blank=True, null=True)),
                ('element_ordering', models.TextField(blank=True, null=True)),
                ('url', models.CharField(blank=True, max_length=200, null=True)),
                ('published', models.BooleanField(default=False)),
                ('elements', models.ManyToManyField(blank=True, to='core.element')),
            ],
        ),
    ]
