# Generated by Django 5.2.8 on 2025-11-23 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='YoutubeSnippet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.CharField(max_length=20)),
                ('thumbnail_url', models.URLField(blank=True, null=True)),
                ('channel_name', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('start_time', models.CharField(blank=True, max_length=20, null=True)),
                ('stop_time', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
