# Configuration file for the Sphinx documentation builder.
# For the full list of built-in configuration values, see the documentation:
# https://www.sphinx-doc.org/en/master/usage/config.html

import os
import sys
from pathlib import Path

# Add the parent directory to the path so we can import dj_palette
sys.path.insert(0, str(Path(__file__).parent.parent))

# -- Project information ---------------------------------------------------
project = "django-palette"
copyright = "2025, Joel O. Tanko"
author = "Joel O. Tanko"
release = "1.0.0"

# The full version, including alpha/beta/rc tags
version = "1.0.0"

# -- General configuration ------------------------------------------------
extensions = [
    "sphinx.ext.autodoc",
    "sphinx.ext.viewcode",
    "sphinx.ext.intersphinx",
    "sphinx_rtd_theme",
]

# Add any paths that contain templates here, relative to this directory.
templates_path = ["_templates"]

# List of patterns, relative to source directory, that should NOT be included when building
exclude_patterns = ["_build", "Thumbs.db", ".DS_Store"]

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
language = "en"

# -- Options for HTML output -----------------------------------------------
html_theme = "sphinx_rtd_theme"
html_static_path = ["_static"]
html_title = "Django Palette Documentation"
html_logo = "../logo.jpg"
html_favicon = None

# Theme options are theme-specific and customize the look and feel of a theme
# further. For a list of options available for each theme, see the documentation.
html_theme_options = {
    "logo_only": False,
    "display_version": True,
    "prev_next_buttons_location": "bottom",
    "style_external_links": False,
    "vcs_pageview_mode": "",
    "style_nav_header_background": "#2980b9",
    # Toc options
    "collapse_navigation": True,
    "sticky_navigation": True,
    "navigation_depth": 4,
    "includehidden": True,
    "titles_only": False,
}

# -- Options for intersphinx extension ------------------------------------
intersphinx_mapping = {
    "python": ("https://docs.python.org/3", None),
    "django": ("https://docs.djangoproject.com/en/stable/", None),
}

# -- Options for autodoc extension ----------------------------------------
autodoc_default_options = {
    "members": True,
    "member-order": "bysource",
    "special-members": "__init__",
    "undoc-members": True,
    "show-inheritance": True,
}

# Exclude certain modules from autodoc
automodule_skip_member = [
    "Meta",
    "DoesNotExist",
    "MultipleObjectsReturned",
]

# Sphinx settings for Django project documentation
django_settings_module = "project.settings"

# Configure Sphinx to not warn about Django imports
suppress_warnings = [
    "app.add_config_value",
]
